export const USER_CONTROLLER_BASE_PATH = 'user'
export const UPDATE_ROLE_PATH = '/role/:id'
export const DELETE_ROLE_PATH = '/role/:id'
export const USER_AUTHENTICATE_PATH = '/authenticate'
export const USER_WORKSHIFT_FINISH_PATH = '/workshifts/:id/finish'
export const USER_PATH = '/'
export const USER_UPDATE_PATH = '/:id'
export const ROLE_PATH = '/role'