export const RESERVE_DELETE_PRICES_PATH = '/price/:id'
export const RESERVE_CONTROLLER_BASE_PATH = 'reserve'
export const RESERVE_PUT_PRICES_PATH = '/price/:id'
export const RESERVE_DISCOUNT_PATH = '/discount'
export const RESERVE_PRICES_PATH = '/price'
export const RESERVE_POST_PATH = '/'
